<a href="https://colab.research.google.com/github/hank199599/Introducing-Python-reading_log/blob/main/Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **程式語言**

它是用來定義電腦程式的形式語言。它是一種被標準化的交流技巧，用來向電腦發出指令。一種能夠讓程式設計師準確地定義電腦所需要使用資料的電腦語言，並精確地定義在不同情況下所應當採取的行動。 最早的程式語言是在電腦發明之前產生的，當時是用來控制提花織布機及自動演奏鋼琴的動作。  
  
以上內容來自維基百科

# 範例1-1 countdown.py  
我們來看一段真正的電腦程式。你認為這段程式在做甚麼事情?

In [ ]:
for countdown in 5,4,3,2,1,"hey!":
  print (countdown)

5
4
3
2
1
hey!


Python有一些特殊的單字與符號 ── for、in、print、逗號、冒號、括號等等它們都是很重要的語法(規則)元素,好消息是,與大多數的電腦語言相比,Python 的語法更好,而且需要記憶的東西較少:它讚起來比較自然,幾乎就像一份食譜。

# 範例1-2  
他會自Python串列中選出一句哈利波特咒語並將它印出來。

In [ ]:
spells =[
         "Riddikulus!",
         "Wingardium Leviosa!",
         "Avada Kedavra!",
         "Expecto Patronum!",
         "Nox!",
         "Lumos!",
]
print(spells[3])

Expecto Patronum!


每一句咒語都是Python字串(被放在引號裡而的一串文字字元)。  
它們都被但號分開並且被故在一個 Python 串列裡面,串列是用方括號來定義的([與])。  
spells 這個字是個變數,它是串列的名稱讓我們可以用它来使一些事情,  
在這個例子中,程式會印出第四個咒語:   
*Expecto Patronum*  
為什麼我們用3來取得第四個? spells 這種 Python串列是一系列的值,欲取得裡面的值,我們必須使用從串列開頭算起的 offcr (偏位值)它的第一個值在offset 0,第四個值則位於offset3

# 範例1-3  
程式會印出 Three Stooges 喜劇中的一句話,不過這段程式用說那句話的人來引用,而不是用那句話在的位置。

In [ ]:
quotes ={
    "Moe": "A wise guy, huh?",
    "Larry": "Ow!",
    "Curly": "Nyuk nyuk!",
  }
stooge ="Curly"
print(stooge, "says:", quotes[stooge])

Curly says: Nyuk nyuk!


## **大一些的程式**

接下來要介紹完全不同的東西了:  
範例 1-4 是執行一系列比較複雜的任務的Python程式。先不用期望你現在就可以瞭解這段程式如何運作,那是這整本書的目的!這個範例的目的是讓你看一下、感受一下典型的而且有點難度的 Python 程式。  
如果你知道其他的電腦語言,可以拿它來比較一下Python。  
雖然你還不認識 Python,你可不可以在閱讀程式後面的解釋之前，大概說出每一行程式在做甚麼事情?  
你已經看過Python串列和字典的例子了，這個程式加入一些其他的功能。

# 例 1-4 archive.py

In [ ]:
import webbrowser
import json
from urllib.request import urlopen

print("Let's find an old website.")
site = input ("Type a website URL:")
era = input ("Type a year, month, and day, like 20150613: ")
url = "http://archive.org/wayback/available?url=%s&timestamp=%s" % (site, era)
response = urlopen(url)
contents = response.read()
text = contents.decode("utf-8")
data = json.loads(text)
try:
  old_site = data["archived_snapshots" ]["closest"]["url"]
  print ("Found this copy: ", old_site)
  print("It should appear in your browsernow.")
  webbrowser.open(old_site)

except:
  print("Sorry, no luck finding", site)

Let's find an old website.
Type a website URL:lolcats.com
Type a year, month, and day, like 20150613: 20151022
Found this copy:  http://web.archive.org/web/20151023052507/http://www.lolcats.com:80/
It should appear in your browsernow.


這一小段Python程式用易懂的程式做了 多事情。雖然你選不知道所有的詞彙。 但接下來的幾章會給你認識它 。以下是每一行做的事情:   
  
1.   匯入的所有程式。(讓這段程式可用) Python 標準程式庫模組 webbrowser
2.   匯入Python 標準程式模組 json 的所有程式。 
3.只從標準程式庫模組 url1ib.request 匯入urlopen a式。
4.空的一行,因為不希望 演程式看起來很擁擠。
5在螢幕上印出一些初始文字。
6. 印出調問URL的文字,並取你輸入的文字, 並將它存入一個稱為 site 7. 印出另一個問題,這一次讀取年、月與日 ,並將它存入一個稱為era 的變数。
7.印出另一個問題，這一次讀取年、月與日，並將它存入一個稱為era 的變数。
8.建立一個稱為url的字串變數,來談Wayback Machine 可用來尋找該網站在你輸入的日期的複本。
9.連接該在URL的web 同服器,並請求持定的 web 服務。
10.取得回應資料,並將它指派給contents 變數。
11. 將contents 解碼成JSON 格式的字串,再指派給 text 變数數。 12.將text 轉換成 data Python 資料結構。
13. 檢查錯誤try(試著)執行接下來的四行,如果有任何失收,就執行最後一行程式 (在except 後面的)。
14.如果我們得到符合日期的網站,從層的 Python字典取得它的值,注意這一行下 三行是粉進來的,Python 用 排來代表它們於上面的try。
15. 印田我們找到的URL。
16. 印出下一行執行之後會發生什麼事。
17.在你的离覽器顯示我們找到的URL .
18.如果在前四行裡面有任何失敗,Python 就會跳到這裡,
19.如果它失敗了,印出一個訊息與我們寻找的網站。這一行內,因為它只能在上面 的except執行時執行。

當我在終端機視窗執行它時,我輸入一個網站 URL與個日期,得到這段輸出文字:  
$ python archive.py

```bash
Let's find an old website.  
Type a website URL: lolcats.com  
Type a year, month, and day, like 20150613: 20151022  
Found this copy: http://web.archive.org/web/20151102055938/http://www.lolcats.com/
```

# 範例1-5  
使用一種稱為 requests 的外部Python軟體包來訪問Internet Archive網站的另種寫法。

In [ ]:
import webbrowser
import requests

print("Let's find an old website. ")
site = input ("Type a website URL: ")
era = input("Type a year, month, and day, like 20150613: ")
url = "http://archive.org/wayback/available?url=%s&timestamp=%s" % (site, era)
response =requests.get (url)
data = response.json()
try:
  old_site = data["archived_snapshots"]["closest"]["url"]
  print("Found this copy: ", old_site)
  print("It should appear in your browser now.")
  webbrowser.open(old_site)
except:  
  print("Sorry, no luck finding", site)

Let's find an old website. 
Type a website URL: lolcats.com
Type a year, month, and day, like 20150613: 20151022
Found this copy:  http://web.archive.org/web/20151023052507/http://www.lolcats.com:80/
It should appear in your browser now.


## 真實世界的Python  
那麼,Python 值得你付出時間和精力來學習嗎? Python 在1991年就出現了(比Java老,比C年輕),一直以來都在最流行的電腦語言排行榜的前五名。很多人受僱撰寫Python 程式,那些程式都是你每天都會用到的正式作品,例如Google、YouTube、Instagram、Netflix與Hulu 我也在許多領域中,用它來製作產品，Python以極高的生產力而聞名吸引了發展快速的組織。  
你可以在許多電腦環境中找到Python包括:  
*   監視器或終端機視窗裡面的命令列
*   圖形化使用者介面(GUI),包括web
*   web,包括用戶端與伺服器端
*   支援大型熱門網站的後端伺服器
*   雲端(由第三方管理的伺服器)
*   行動裝置
*   嵌入式裝置
  
Python 程式包括一次性的腳本(例如在本章出現過的那些),和上百萬行的系統
在2018年的 Python Developers' Survey (hutps://oreilly8vkZy)裡面,你可以看到代表 Python 目前在電腦世界的地位的數據和圖表。

我們將會看到它在網站、系統管理和資料操作之中的應用,在最後幾章,我們將會看到Python 在藝術、科學和商業領域中的具體用途。